# Workspace rules
workspace = 1, monitor:HDMI-A-1
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:eDP-1

# Window rules
#windowrule= workspace 1, class:^(floorp)$
windowrule =  workspace 1, match:class ^(floorp)$
windowrule= workspace 1, match:class ^(firefox)$
windowrule= workspace 3, match:class ^(com.mitchellh.ghostty)$
windowrule= workspace 10, match:class ^(spotify)$
windowrule= workspace 9, match:class ^(discord)$
windowrule= workspace 8, match:class ^(org.keepassxc.KeePassXC)$
windowrule= workspace 6, match:initial_class ^(Lxappearance)$
windowrule= workspace 6, match:class ^(blueberry.py)$
windowrule= workspace 9, match:initial_class ^(Whatstron)$
windowrule= workspace 4, match:class ^(thunar)$
windowrule= workspace 2, match:initial_class ^(unityhub)$
windowrule= workspace 2, match:initial_class ^(VSCodium)$
windowrule= workspace 2, match:initial_class ^(com-jetbrains-toolbox-entry-ToolboxEntry)$
windowrule= workspace 5, match:title Waydroid

windowrule= fullscreen on, match:title Waydroid
windowrule= float on, match:class ^(org.speedcrunch.speedcrunch)$

# Scratchpad rules
windowrule= float on,size 35% 35%,match:class (ghostty.Btop)
windowrule= float on,size 40% 40%,match:class (ghostty.ScratchTerm)

# Blur window rules
windowrule = opacity 0.95, match:class ^(floorp)$
windowrule = opacity 0.95, match:class ^(firefox)$
windowrule = opacity 0.8, match:class ^(thunar)$
windowrule = opacity 0.9, match:class ^(com.obsproject.Studio)$
windowrule = opacity 0.85, match:class ^(discord)$
windowrule = opacity 0.85 , match:class ^(Whatstron)$
windowrule = opacity 0.85, match:class ^(org.keepassxc.KeePassXC)$
windowrule = opacity 0.7, match:class ^(spotify)$

# Xwaylandvideobridge rules
windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}
