#preload = ~/Pictures/wallpaper.jpg
#wallpaper = ,~/Pictures/wallpaper.jpg
#splash = true

wallpaper {
	monitor = eDP-1
	path = ~/Pictures/wallpaper.jpg
}
wallpaper {
	monitor = HDMI-A-1
	path = ~/Pictures/wallpaper.jpg
}
